<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\Schema;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\PermissionRegistrar;

/** Variation orders were removed from ProTor: drop the table and its Shield permissions. */
return new class extends Migration
{
    public function up(): void
    {
        Schema::dropIfExists('variation_orders');

        Permission::query()->where('name', 'like', '%:VariationOrder')->delete();
        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }

    public function down(): void
    {
        // Recreate the empty table from its original migration (permissions are regenerated by Shield).
        (require database_path('migrations/2026_09_30_000004_create_variation_orders_table.php'))->up();
    }
};
